import { ArrowRight, Check, CircleDollarSign, Clock3, Scale, Send } from "lucide-react";
import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { ProjectTable } from "@/components/project-table";
import { projects } from "@/lib/projects";

export default function DashboardPage() {
  return <><PageHeader eyebrow="ESCROW / OVERVIEW" title="Project clearing desk" /><section className="clearingStrip" aria-label="Escrow summary"><div className="totalBlock"><span className="metricLabel">LOCKED IN ACTIVE PROJECTS</span><strong><small>$</small>19,300<span>.00</span></strong><p><b>3 contracts</b> protecting 9 milestones</p></div><div className="checkpointBlock"><p className="traceLabel"><span /> MILESTONE RELEASE TRACE</p><div className="traceLine" aria-hidden="true"><i /><i /><i /><i /><i /></div><dl className="checkpointStats"><div><dt>Awaiting your action</dt><dd>2</dd></div><div><dt>In dispute</dt><dd>1</dd></div><div><dt>Released</dt><dd>3</dd></div></dl></div></section><section className="stateRail" aria-label="Milestone states"><div><Clock3 /><span>FUNDED</span><strong>2</strong><small>$5,500 ready for work</small></div><div><Send /><span>SUBMITTED</span><strong>1</strong><small>Review due in 2 days</small></div><div><Scale /><span>DISPUTED</span><strong>1</strong><small>$6,000 with resolver</small></div><div><CircleDollarSign /><span>RELEASED</span><strong>3</strong><small>$9,000 paid out</small></div></section><section className="sectionBlock"><div className="sectionHeading"><div><h2>Active projects</h2><p>Every project is an independent stablecoin escrow contract.</p></div><Link href="/dashboard/projects">View all projects <ArrowRight size={16} /></Link></div><ProjectTable rows={projects} /></section><section className="activitySection"><div className="activityTitle"><Check size={19} /><div><h2>Action queue</h2><p>Contract deadlines and decisions</p></div></div><ol className="activityLog"><li data-tone="warning"><time>TODAY</time><i /><div><strong>Review “Identity system”</strong><span>Approve, dispute, or allow automatic release in 2 days.</span></div></li><li><time>SEP 28</time><i /><div><strong>Submit “Storefront”</strong><span>Attach a delivery URL and immutable content hash.</span></div></li><li data-tone="warning"><time>OPEN</time><i /><div><strong>Implementation dispute</strong><span>Waiting for the designated resolver.</span></div></li></ol></section></>;
}
